# Generated by Django 5.2.6 on 2025-11-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_stars_precision'),
        ('providers', '0002_initial'),
    ]

    operations = [
    ]
