# Generated by Django 5.2.6 on 2025-09-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='servide_types',
            new_name='service_types',
        ),
        migrations.AddField(
            model_name='provider',
            name='cpf',
            field=models.CharField(default=1, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
