# Generated by Django 5.2.6 on 2025-11-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_providerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='providers/images/'),
        ),
    ]
