# Generated by Django 5.2.6 on 2025-11-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_provider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nome da empresa ou apelido público do provider', max_length=100, null=True),
        ),
    ]
