# Generated by Django 5.2.6 on 2025-11-30 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_provider_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cpf_cnpj',
            field=models.CharField(default="", help_text='CPF ou CNPJ do provider', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='cpf_cnpj',
            field=models.CharField(default="", max_length=18),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nome da empresa ou apelido público do provider', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='providerapplication',
            unique_together={('applicant', 'cpf_cnpj')},
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='cpf',
        ),
    ]
