# Generated by Django 5.2.6 on 2025-11-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_remove_provider_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='cpf_cnpj',
            field=models.CharField(default=0, help_text='CPF ou CNPJ do provider', max_length=18, unique=True),
        ),
    ]
