# Generated by Django 5.2.6 on 2025-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_alter_providerapplication_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cpf_cnpj',
            field=models.CharField(default='', help_text='CPF ou CNPJ do provider', max_length=18, unique=True),
        ),
    ]
