# Generated by Django 5.2.6 on 2025-11-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='description',
        ),
    ]
