# Generated by Django 5.2.6 on 2025-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0004_servicerequest_provider_servicerequest_status_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
