# Generated by Django 5.2.6 on 2026-05-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicerequests', '0006_servicerequest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='location',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
